### PR TITLE
Add support for multiple jobs

### PR DESCRIPTION
**Pull request by urbainn**
Hello,

this is mostly a draft for now, but I'm working on adding support for multiple jobs, with the ability to switch between them, and even create new ones.

I tried going for a very simple and intuitive design, that can be rolled back easily if it doesn't really fit the app. switching between two different jobs is done using a tab bar at the top, which also contains a '+' button (not yet implemented) to create a new job.

Here is what it looks like as of right now:
image

peek-sdujkkkfhsdjkfhsdkjfsd

**this also creates a few questions:**
- should the 'Update' button only process the currently selected job, or should it process all jobs? maybe a separate 'Process all jobs' button could be added?
- each job has its own settings, but there is only one centralized 'settings' screen: should it display all settings for all jobs separately? or maybe only display the settings of the currently selected job, I'm not sure how to proceed with this.
- should the user be able to delete a job? if so, how and where should it be handled?

with these new changes, the `HomeScreen` widget was getting a bit large, so I've added a 'Home Job Widget' that contains both the job playlist display as well as the recipe. I hope this is okay, and I can of course rollback this change if you'd like all of this to be kept in the `HomeScreen` widget.

there's still a lot of work left for this to be fully compatible, but before committing to it I wanted to make sure this respects your vision for the app, and make sure I'm going in the right direction.

thank you for reading.

### CODE REVIEW

**Comment by urbainn** [comment]
just merged the recent changes made by @riverscuomo 

I've also slightly modified the look of the tab bar, as well as how the scrolling works:

image

new scrolling:

Peek 2024-08-08 14-58

**Comment by riverscuomo** [comment]
This looks really nice!!

A few thoughts:

1. I was thinking we'd add the multiple jobs feature after we're super happy with how a single job works, just to make it easier on ourselves as developers. But it's tempting to merge this now.
2. Ultimately, I think we limit the number of jobs to 2 or 3. Otherwise we're defeating one of the purposes of Spotkin--to simplify music discovery.
3. I'm trying to adhere to a 'mobile first' design so I set my chrome like this:

image

**Comment by riverscuomo** [comment]
> should the 'Update' button only process the currently selected job, or should it process all jobs? maybe a separate 'Process all jobs' button could be added?

the primary update button should update only one job.  Maybe somewhere else we can have an update all button.


> each job has its own settings, but there is only one centralized 'settings' screen: should it display all settings for all jobs separately? or maybe only display the settings of the currently selected job, I'm not sure how to proceed with this.
Yeah there should be a different setting screen generated for each playlist. I suppose we'll have to move the settings icon button down out of the app bar.

> should the user be able to delete a job? if so, how and where should it be handled?
Yes, Users should be able to delete a job.

**Comment by urbainn** [comment]
thanks a lot for the feedback and answers, there's still a lot of work to do (and bugs to fix!) but now that I have all the answers I needed, I'll get back to work and update this PR once everything's ready.

**Comment by urbainn** [comment]
Hey,
This PR should (finally) be ready for review, here are a few key updates I've made since the last push:

- Creating new jobs, with the '+' button in the tab bar, button that only appears if all jobs have a target playlist and the maximum number of jobs isn't reached (adjustable with the `maxJobs` variable in the home screen file):
Peek 2024-08-12 23-10

- Improved navigation between jobs with the swipe gesture:
Peek 2024-08-12 23-13

- Each job has its own settings.

- Importing a backup dynamically updates the tab bar.

- Clicking the 'update' button will process the current job, and display the success/failed status text only on that job:
Peek 2024-08-12 23-19

I've also added a `index` field to the `process_jobs` payload to the backend that contains the index of the current job in order of creation, with the objective to eventually add support for multiple jobs here as well. The idea was to store a list of jobs in the user's data, and use the index to know which job to update. something like `job = all_data[user_id]['jobs'][index]` in `server.py` if that makes sense. but there's probably better ways to do it.

Back to the flutter app, I really hope this is a positive change and that (hopefully) it doesn't contain any bug that I didn't notice.
If there's anything wrong about the way I've implemented some things, please let me know.

Urbain.

**Comment by riverscuomo** [comment]
Awesome! Let's try this. Sorry for the slow response.

**Comment by urbainn** [comment]
It's all good. thanks for merging the changes.

**Pull request merged**
